# -*- coding: utf-8 -*-
"""Bake & Cook House Forecasting 2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11rO5N5siHrfuVAWlNFjIM6Uh65dbwOns
"""

from sklearn.linear_model import LogisticRegression
import joblib
import pandas as pd

# 1. Load updated dataset
df_updated = pd.read_csv('updated_bakery_sales.csv')

# Rename the last column to 'Target' if it's unnamed
df_updated = df_updated.rename(columns={df_updated.columns[-1]: 'Target'})

# 2. Re-fit model on fresh historical data
feature_cols = [
    'Price', 'Day_of_Week', 'Is_Weekend',
    'Sales_Last_7_Days', 'Same_Day_Last_Week'
] + [col for col in df_updated.columns if col.startswith('Item_Name_')]

model_updated = LogisticRegression(
    class_weight='balanced',
    C=0.5,
    max_iter=1000,
    random_state=42
)
model_updated.fit(df_updated[feature_cols], df_updated['Target'])

# 3. Overwrite artifact
updated_artifact = {
    'model': model_updated,
    'feature_cols': feature_cols,
    'threshold': 0.45
}

joblib.dump(updated_artifact, 'bakery_model.pkl')
print("✅ Model successfully retrained on new dataset!")